when:
  - event: push
    branch:
      - main
      - server-*
  - event: manual

labels:
  type: nixos-sync
  host: dell-latitude-7390-server

steps:
  - name: nixos-rebuild-latitude-7390-server
    image: bash
    commands:
      - sudo nixos-rebuild switch --flake .#dell-latitude-7390-server
