name: nixos-rebuild-latitude-7390-server

on:
  push:
    branches:
      - main
      - "server-*"
  workflow_dispatch:

jobs:
  sync:
    runs-on: latitude-7390-server
    steps:
      - uses: actions/checkout@v4
      - name: Apply NixOS configuration
        run: /run/wrappers/bin/sudo /run/current-system/sw/bin/nixos-rebuild switch --flake .#dell-latitude-7390-server
