name: nixos-rebuild-latitude-7390-server

on:
  push:
    branches:
      - main
      - "server-*"
  workflow_dispatch:

jobs:
  sync:
    runs-on: latitude-7390-server
    steps:
      - uses: actions/checkout@v4
      - name: Apply NixOS configuration
        env:
          PATH: /run/wrappers/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/bin:/bin
        run: sh apply-latitude-7390-server.sh
